spring:
  # 数据源基本配置
  datasource:
    # 数据库账号
    username: root
    # 数据库密码
    password: 123456
    # 连接引擎
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接路径
    #当mysql返回的时间出现问题时，添加&serverTimezone=GMT在url后面选择时区
    url: jdbc:mysql://localhost:3306/db_startxie_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
#    url: jdbc:mysql://localhost:3306/db_startxie?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    # 使用druid数据源 若不加上type则默认使用tomcat数据源
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: UTF-8

    # 数据源其他高级配置

    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
